name: nsvtest
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: run command
      shell: bash
      run: echo "hello world"
    - name: run command
      shell: bash
      run: echo "Hi Sandeep"
